version: "3"

services:

  mongodb:
    container_name: chat-demo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo-db
    networks:
      - network
  minio:
    image: bitnami/minio:2021.4.22
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password


networks:
  network:

volumes:
  postgres-volumes:
